version: 2

models:

  - name: int_ratings_pit
    description: >
      Builds rating validity windows (valid_from → valid_to)
      using LEAD() to prepare PIT resolution.
    columns:
      - name: buyer_tax_id
        tests:
          - not_null

      - name: rating
        tests:
          - not_null

      - name: valid_from
        tests:
          - not_null

      - name: valid_to
        tests:
          - not_null

    tests:
      - unique:
          column_name: "(buyer_tax_id || '-' || valid_from)"
      - relationships:
          arguments:
            to: ref('stg_ratings')
            field: buyer_tax_id


  - name: int_assets_pit
    description: >
      Performs Point-in-Time (PIT) join between assets and rating windows.
      Ensures origin_rating is correct for asset creation date.
    columns:
      - name: buyer_tax_id
        tests:
          - not_null

      - name: created_at
        tests:
          - not_null

      - name: origin_rating
        description: "Rating active at the time of asset origination."
        tests:
          - not_null

    tests:
      - relationships:
          arguments:
            to: ref('stg_assets')
            field: buyer_tax_id
      - relationships:
          arguments:
            to: ref('dim_rating')
            field: origin_rating
