version: 2

models:

  - name: int_ratings_pit
    description: >
      Builds rating validity windows (valid_from → valid_to)
      using LEAD() to prepare PIT resolution.
    columns:
      - name: buyer_tax_id
        tests:
          - not_null

      - name: rating
        tests:
          - not_null

      - name: valid_from
        tests:
          - not_null

      - name: valid_to
        tests:
          - not_null

    tests:
      - unique:
          column_name: "(buyer_tax_id || '-' || valid_from)"


  - name: int_assets_pit
    description: >
      Performs Point-in-Time (PIT) join between assets and rating windows.
      Ensures origin_rating is correct for asset creation date.
    columns:
      - name: buyer_tax_id
        tests:
          - not_null:
              severity: warn

      - name: created_at
        tests:
          - not_null:
              severity: warn

      - name: origin_rating
        description: "Rating active at the time of asset origination."
        tests:
          - not_null:
              severity: warn

      - name: face_value
        description: "Original financial value of the asset."

      - name: settled_at
        description: "Timestamp when the asset was settled. Null indicates unpaid."

      - name: due_date
        description: "Date when the asset was due. Used to determine overdue status."

      - name: seller_name
        description: "Name of the seller (originator) of the asset."

      - name: buyer_state
        description: "Geographical segment of the buyer, used for aggregation."

      - name: collection_status
        description: "Status of the asset's repayment or collection."
