version: 2

models:

  - name: int_assets_pit
    description: "Assets com rating point-in-time"
    columns:
      - name: created_at
        description: "Timestamp when the asset was created (origination date)."
      - name: face_value
        description: "Original financial value of the asset."
      - name: settled_at
        description: "Timestamp when the asset was settled. Null indicates unpaid."
      - name: due_date
        description: "Date when the asset was due. Used to determine overdue status."
      - name: buyer_tax_id
        description: "Unique identifier for the buyer, used to match historical ratings."
      - name: seller_name
        description: "Name of the seller (originator) of the asset."
      - name: buyer_state
        description: "Geographical segment of the buyer, used for aggregation."
      - name: collection_status
        description: "Status of the asset's repayment or collection."
      - name: origin_rating
        description: |
          Rating assigned to the buyer at the time the asset was originated.
          Selected using a point-in-time (PIT) lookup: the most recent rating
          before or on the asset creation timestamp.
        tests:
          - not_null:
              severity: warn
      - name: cohort_month
        description: |
          Monthly cohort derived from asset creation date. Used for aggregation
          and performance tracking across time.
