version: 2

models:

  - name: stg_assets
    description: "Cleans and standardizes raw asset data. Removes duplicates and invalid rows."
    columns:
      - name: created_at
        description: "Timestamp when the asset was originated."
        tests:
          - not_null

      - name: due_date
        description: "Due date of the asset."

      - name: face_value
        description: "Nominal value of the asset."
        tests:
          - not_null

      - name: buyer_tax_id
        description: "Unique buyer identifier."
        tests:
          - not_null

      - name: seller_name
        description: "Seller associated with the asset."

      - name: buyer_state
        description: "Buyer state or segment grouping."

      - name: normalized_collection_status
        description: "Normalized collection status (Processing ≈ Settled)."

    tests:
      - unique:
          column_name: "(buyer_tax_id || '-' || created_at)"
          config:
            severity: warn


  - name: stg_ratings
    description: "Cleans and standardizes raw rating history. Ensures one rating event per timestamp per buyer."
    columns:
      - name: buyer_tax_id
        tests:
          - not_null

      - name: rating
        tests:
          - not_null

      - name: rating_created_at
        tests:
          - not_null

    tests:
      - unique:
          column_name: "(buyer_tax_id || '-' || rating_created_at)"
          config:
            severity: warn
