version: 2

models:

  - name: mrt_cost_of_risk
    description: >
      Aggregated Cost of Risk per (cohort_month, segment, seller_name).
      Applies business logic: settled -> 0%, default -> 100%, else rating-based rate.
    columns:
      - name: cohort_month
        tests:
          - not_null

      - name: segment
        tests:
          - not_null

      - name: seller_name
        tests:
          - not_null

      - name: total_face_value
        tests:
          - not_null

      - name: cost_of_risk
        tests:
          - not_null

      - name: avg_provision_rate
        tests:
          - not_null

      - name: n_assets
        tests:
          - not_null

    tests:
      - unique:
          column_name: "(cohort_month || '-' || segment || '-' || seller_name)"
